spring.datasource.url=jdbc:postgresql://localhost:5432/om_game
spring.datasource.username=om_user
spring.datasource.password=om_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

server.port=8080
